spring:
  application:
    name: cloudcart-disputes

  datasource:
    url: jdbc:h2:mem:disputedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true

  h2:
    console:
      enabled: false

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      read-unknown-enum-values-as-null: false
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

server:
  error:
    include-message: never
    include-stacktrace: never
    include-exception: false
    include-binding-errors: on_param

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

logging:
  level:
    com.cloudcart.disputes: INFO
    org.springframework.web: WARN
